/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aubo_aubojdr_RobotDrv */

#ifndef _Included_com_aubo_aubojdr_RobotDrv
#define _Included_com_aubo_aubojdr_RobotDrv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aubo_aubojdr_RobotDrv
 * Method:    initialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aubo_aubojdr_RobotDrv_initialize
  (JNIEnv *, jobject);

/*
 * Class:     com_aubo_aubojdr_RobotDrv
 * Method:    uninitialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aubo_aubojdr_RobotDrv_uninitialize
  (JNIEnv *, jobject);

/*
 * Class:     com_aubo_aubojdr_RobotDrv
 * Method:    createContext
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aubo_aubojdr_RobotDrv_createContext
  (JNIEnv *, jobject);

/*
 * Class:     com_aubo_aubojdr_RobotDrv
 * Method:    destoryContext
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_aubo_aubojdr_RobotDrv_destoryContext
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_aubo_aubojdr_RobotDrv
 * Method:    login
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_aubo_aubojdr_RobotDrv_login
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     com_aubo_aubojdr_RobotDrv
 * Method:    logout
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_aubo_aubojdr_RobotDrv_logout
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_aubo_aubojdr_RobotDrv
 * Method:    moveJ
 * Signature: (I[D)I
 */
JNIEXPORT jint JNICALL Java_com_aubo_aubojdr_RobotDrv_moveJ
  (JNIEnv *, jobject, jint, jdoubleArray);

/*
 * Class:     com_aubo_aubojdr_RobotDrv
 * Method:    moveL
 * Signature: (I[D)I
 */
JNIEXPORT jint JNICALL Java_com_aubo_aubojdr_RobotDrv_moveL
  (JNIEnv *, jobject, jint, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
